"""empty message

Revision ID: 57836fe431bf
Revises: 0fffd8de635f
Create Date: 2021-08-08 11:05:36.363513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57836fe431bf'
down_revision = '0fffd8de635f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('dateCreated', sa.DateTime(), nullable=True))
    op.add_column('venue', sa.Column('dateCreated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'dateCreated')
    op.drop_column('artist', 'dateCreated')
    # ### end Alembic commands ###
