"""empty message

Revision ID: e114c4b1aae4
Revises: fb01105550e5
Create Date: 2021-08-09 10:11:05.241004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e114c4b1aae4'
down_revision = 'fb01105550e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'datesAvailable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('datesAvailable', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
