"""empty message

Revision ID: fb01105550e5
Revises: 57836fe431bf
Create Date: 2021-08-08 16:33:36.487645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb01105550e5'
down_revision = '57836fe431bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('datesAvailable', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'datesAvailable')
    # ### end Alembic commands ###
